### ISSUE TITLE
Multiple img with jsrc doesn't work

### ISSUE THREAD

**Issue by usmjc** [shabeer-ali-m/jPut#12]
Hi !
Love this plugin, but i've encountered a problem when setting multiple img-src's from JSON data.
As we know having the jsrc rather than src attribute will ensure that the browser won't try and load the image from the server before the json-data is ready.

Example JSON : 
jPut.list.data = [{"name":"data1",
 "icon":MODEL.staticUri+"/icons/icon_data1.png",
 "currency":MODEL.staticUri+"/icons/ico_coins.png"},
"name":"data2",
 "icon":MODEL.staticUri+"/icons/icon_data2.png",
 "currency":MODEL.staticUri+"/icons/ico_bills.png"}];

Template html:
<div id="list" jput="list" jput-jsondata='[]'>
  <div id="row{{index}}">
    <img id="icon" jsrc="{{json.icon}}"/>
    <img id="currency_icon" jsrc="{{json.currency}}" />
  </div>
</div>

The second (#currency_icon) jsrc gets ignored. And when changing the 'jsrc' to 'src' it will work just fine, except that gets hit for the ressource : 'http://example.com/{{json.currency}}'.

Any ideas ? Or if you can just provide an un-minified version of the jput-2.js, then i can look into this myself :-)

**Comment by shabeer-ali-m** [comment]
Hi 
Can you put your code in jsfiddle

**Comment by usmjc** [comment]
sure thing !

https://jsfiddle.net/jc_usm/rod13a4k/1/

**Comment by shabeer-ali-m** [comment]
Its a bug. Thank you for reporting. Please update the jput-2.js

**Comment by jacoblaier** [comment]
Yeah, saw that bug too quite fast. No biggie. 
Got to learn about jsbeautifier.org in the process. Thanks for that :-)
And thanks for the fast fix.
