### ISSUE TITLE
call jPut function with option not work

### ISSUE THREAD

**Issue by winweb** [shabeer-ali-m/jPut#13]
I want create template div for add table row. I try call jPut function with option but it not work.

``` html
<div jput="tbody_template">
 <tr>
  <td>{{json.name}}</td>
  <td>{{json.score}}</td>
 </tr>
</div>

<table border=1>
 <tbody id="tbody">
 </tbody>
</table>
```

``` javascript
var json = [{"name": "name1","score":"30"},{"name": "name2","score":"50"}];
$("#tbody").jPut({
    jsonData:json,
    name:"tbody_template"
});
```

jsfiddle : https://jsfiddle.net/win_web/4w1gwLdv/

**Comment by winweb** [comment]
I checked your link for suggest in issue #5 had error also.

jsfiddle : http://jsfiddle.net/89s4qcdz/1/

**Comment by winweb** [comment]
I disable auto jPut by set jPut.auto = 0. 

jPut can show output result but html element in template div not render.

jsfiddle : http://jsfiddle.net/win_web/9ufq0qf2/

**Comment by winweb** [comment]
i can solve html element in template div not render.

change

```
<div jput="tbody_template">
 <tr>
  <td>{{json.name}}</td>
  <td>{{json.score}}</td>
 </tr>
</div>
```

to

```
<script jput="tbody_template">
 <tr>
  <td>{{json.name}}</td>
  <td>{{json.score}}</td>
 </tr>
</script>
```

jsfiddle : http://jsfiddle.net/win_web/9ufq0qf2/4/

**Comment by Hacksli** [comment]
Думаю это поможет решить проблему: use <template></template> 

<template jput="tbody_template">
  <tr>
    <td>{{json.name}}</td>
    <td>{{json.score}}</td>
  </tr>
</template>

<table border=1>
  <tbody id="tbody">
  </tbody>
</table>

$(document).ready(function(){
//jPut.auto=0;
//$.jPut.auto=0;
var json = [{"name": "name1","score":"30"},{"name": "name2","score":"50"}];
  //jPut Code
  $('#tbody').jPut({
    jsonData:json,
    name:'tbody_template',
    // dataName:'group',
    error:function(e){
      console.log(e);
    }
  });   
});

**Comment by Hacksli-old** [comment]
use template tag <img src="http://i.piccy.info/i9/4bed60e1dba0001ac7b6e126d20c42d5/1474026761/9118/1070595/template_240.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2016-09-16-11-52/i9-10285901/240x182-r" target="_blank"><img src="http://i.piccy.info/a3/2016-09-16-11-52/i9-10285901/240x182-r/i.gif" alt="" border="0" />

http://jsfiddle.net/Hacksli/89s4qcdz/6/

**Comment by winweb** [comment]
thanks @Hacksli
