### ISSUE TITLE
Displaying the data as img src makes invalid request

### ISSUE THREAD

**Issue by InToSSH** [shabeer-ali-m/jPut#14]
Hi,
I am using jPut to dynamically add rows to the cart in eshop, with image, this is the simplified template:

```
<tbody jput="cart" jput-jsondata='[]'>
                        <tr>
                            <td><img class="cart-img" src="@{{ json.image }}"></td>
                            <td>@{{ json.title }}</td>
                            <td>@{{ json.prices.display.price_wc }}</td>
                        </tr>
</tbody>
```

However because the DOM loads before javascript, the browser is creating invalid GET request to 
`example.com/{{ json.image }}`, is there anything I could do about this?

Thank you.

**Comment by jacoblaier** [comment]
write it like this : jsrc="@{{ json.image }}"

**Comment by InToSSH** [comment]
@usmjc awesome, thanks a lot! :) didn't know about that.
