### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by mavatko** [shabeer-ali-m/jPut#5]
hi,
generating tables is not possible, if you have only tr td elements in your template div

div jput="table"
tr
td {{id}}   /td
td {{url}} /td
/tr 

this will return  only {{id}} {{url}}

**Comment by keyeh** [comment]
Shabeer, that table example was very useful. FYI if anyone's looking for how to have table headers too, this is how I did it:


	<table>
		<tbody jput="template">
			<tr>
				<td>{{req_FirstName}}</td>
				<td>{{req_LastName}}</td>
			</tr>
		</tbody>
	</table>




	<table>
		<thead>
			<tr>
				<td>req_FirstName</td>
				<td>req_LastName</td>
			</tr>
			<tbody id="output">
			</tbody>
		</thead>
	</table>

**Comment by shabeer-ali-m** [comment]
Thank you for your contribution.
