### ISSUE TITLE
Template image tags

### ISSUE THREAD

**Issue by pxdunn** [shabeer-ali-m/jPut#7]
Is there a way to use script tags rather than html for the markup so the page doesn't make empty requests for image ```src``` on load?

Example:
```
<script jput="template-name" type="text/x-handlebars-template">
  <div class="item">
    <h1>{{title}}</h1>
    <div class="item-body">
      {{body}}
    </div>
  </div>
</script>
```

Issue explained here: [Prevent mustache.js templates from loading images using template syntax](http://stackoverflow.com/questions/20626040/prevent-mustache-js-templates-from-loading-images-using-template-syntax)

**Comment by shabeer-ali-m** [comment]
Hi,
In jPut instead of "src" you can use "jsrc" tag. While render it will convert to src.

**Comment by pxdunn** [comment]
I missed that part... Awesome, thank you!
