### ISSUE TITLE
Set a checkbox with jPut

### ISSUE THREAD

**Issue by bazzilic** [shabeer-ali-m/jPut#8]
I couldn't figure out an elegant way to set a checkbox status using jPut. My current workaround is

```html
<div jput="chckboxDiv" jput-singledata="true">
        {{json.BooleanValue?'<input id=chckbx type=checkbox checked>':'<input id=chckbx type=checkbox>'}}
</div>
```

This works but there might be a better way to do that. Do you have any ideas?

**Comment by shabeer-ali-m** [comment]
Here is the best way to do : 
```html
      <div jput="chckboxDiv" jput-singledata="true" jput-jsondata='{"boolvalue":true}'>
         <input type="checkbox" name="vehicle" {{json.boolvalue?'checked':''}} />
      </div>
```
And you can update checkbox by updating ```boolvalue```.

```javascript
jPut.chckboxDiv.update("boolvalue",false);
```

**Comment by bazzilic** [comment]
What you suggested was the first thing I tried to do. I couldn't get it to work, instead of `checked` I get `<input type="checkbox" =""="">` in IE11 and `<input type="checkbox" ="">` in Chrome.

**Comment by shabeer-ali-m** [comment]
I tried its working fine. You can check the below fiddle link which i demonstrate your requirement. Also i will look into your issue.

https://jsfiddle.net/nvm765z8/

**Comment by bazzilic** [comment]
I receive the data from AJAX, so this fiddle is closer to what I have: https://jsfiddle.net/3kxrnqt9/ And it doesn't work.

**Comment by bazzilic** [comment]
Wrong link. The correct is https://jsfiddle.net/3kxrnqt9/3/
And I was wrong, it does work. But for some reason I can't make it to work on my page. I'll investigate.

**Comment by shabeer-ali-m** [comment]
I got the issue. Thank you for your support. I will fix the bug and update jPut soon.
