### ISSUE TITLE
jPut Change Selection

### ISSUE THREAD

**Issue by erayaydin** [shabeer-ali-m/jPut#9]
Hello,
I'm using Laravel. My view engine (Blade) is using ``{{ }}``. Because of this jPut overlap with Laravel Blade. Can I change `` {{ `` and `` }} `` selectors with set option.

**Comment by shabeer-ali-m** [comment]
Hi,
Download the latest one then you can change the expression to ```{[exp]}``` using ```expression```. set expression to "exp2".
Demo link : http://shabeer-ali-m.github.io/jPut/v2demo/expression/

**Comment by erayaydin** [comment]
Thank you, nice work :smile: :+1:
